### ISSUE TITLE
Modules installed from github fail

### ISSUE THREAD

**Issue by Rich-Harris** [marcello3d/node-safestart#13]
If I install a package from github, like

```bash
npm i -S Rich-Harris/regl#es-modules
```

then I get the following mismatch error:

> expected: github:rich-harris/regl#es-modules, got: rich-harris/regl#es-modules

Changing `index.js` like this seems to work, but maybe I've misunderstood the problem?

```diff
- expectedVersion = expectedVersion.replace(/^git\+https/, 'git')
+ expectedVersion = expectedVersion.replace(/^git\+https/, 'git').replace('github:', '')
```

**Comment by marcello3d** [comment]
I think this is reasonable—kinda depends if npm ever adds support for git hosting besides github. The danger would be the odds of collision in that scenario (e.g. moving a project from `github:` to `gitlab:`).

If you install `npm i -S github:Rich-Harris/regl#es-modules` does it make a difference?

**Comment by Rich-Harris** [comment]
Ah, see what you mean re collision danger. Maybe it's better to just cross that bridge when we come to it?

> If you install npm i -S github:Rich-Harris/regl#es-modules does it make a difference?

Weirdly, no, it gets stripped off of `pkg._from`.

Should I send a PR? Cheers

**Comment by marcello3d** [comment]
That'd be great

**Comment by Rich-Harris** [comment]
Ok, so it turns out that in the current version (I modified my fork, which it turns out was very out of date) you're using `pkg._resolved` rather than `pkg._from`. So I guess the version specified in `package.json` also has to be resolved? Not sure how that happens... an alternative would be to allow an `exclude` option like so...

```js
safestart(__dirname, { exclude: ['regl'] })
```

Thoughts?

**Comment by marcello3d** [comment]
Hmm ya that's a great idea. Escape hatch for those that need it
