### ISSUE TITLE
Needs to handle versions with leading 0s

### ISSUE THREAD

**Issue by theogravity** [marcello3d/node-safestart#4]
See issue here:

https://github.com/facebook/react/issues/2811

tl;dr

An app requires a package version that reads `7001.0001.0000` but when `npm` downloads the package, it  will cache the package as `7001.1.0` (which will also imprint the `version` field in the package's `package.json` as `7001.1.0` instead of `7001.0001.0000`) resulting in a mismatch.

**Comment by marcello3d** [comment]
fixed by f00534813
